name: run-debug

on:
  pull_request:
  push:
    branches: [main]

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements.txt

    - name: Install Jax with CPU
      run: |
        pip install --upgrade "jax[cpu]==0.4.13"

    - name: Train on debug dataset
      run: WANDB_MODE=disabled python train.py --config experiments/dibya/debug_config.py --name debug
