name: Run Debug Dataset

on:
  pull_request:
  push:
    branches: [main, test-debug-ci]

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements.txt

    - name: Jax with CPU
      run: |
        pip install --upgrade "jax[cpu]==0.4.13"

    - name: Train on debug dataset
      run: WANDB_MODE=disabled python train.py --config config.py:ci_debug_dataset --name debug

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
